# Generated by Django 5.2.17 on 2026-10-04 22:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='titre')),
                ('done', models.BooleanField(default=False, verbose_name='terminée')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='créée le')),
            ],
            options={
                'ordering': ['done', '-created_at'],
            },
        ),
    ]
